### ISSUE TITLE
Service files should be in /usr/lib on aarch64

### ISSUE THREAD

**Issue by abranson** [pastillilabs/sonar#1]
Although the new aarch64 version of SailfishOS has moved all binaries to /usr/lib64, other files such as systemd unit files have remained in /usr/lib. The sonar service is currently unable to start on 64bit devices because its unit file isn't found.

The rpm macro to use the right dir is %{_userunitdir}

**Comment by hhaveri** [comment]
Thanks for this piece of information!

On aarch64 situations-sonar.service file is currently installed to /etc/systemd/system and harbour-situations2application.service to /usr/lib64/systemd/user. So I assume you are talking about the latter?

Would be nice to have a 64 bit emulator to test these against :)

**Comment by hhaveri** [comment]
Should be fixed with the latest commit
