### ISSUE TITLE
Installation of sonar directly in the Sailfish app doesn't work

### ISSUE THREAD

**Issue by speedy-10** [pastillilabs/sonar#2]
Hi, using Sailfish OS 4.4.0.64, I installed Situations from the Jolla shop.  External source is activated for installation.
In the Situations-menu > “i”, I tap on “Sonar install”, nothing happens. After several tries, I had to install it directly from github.
If it is a bug of Situations or Sonar, it would be nice, if it could be fixed.

**Comment by hhaveri** [comment]
Hi, the issue is caused by the addition of sandboxing to Sailfish, which prevents the current way used to launch the Sonar installer. There is a known fix for that, but since sandboxing causes also several other issues, the focus has been on building foundations to make the whole app work better under sandboxing. It will still take a lot of time though, so perhaps there will be need to update this one issue before any bigger changes...

**Comment by speedy-10** [comment]
Perpaps a simle hint ins FAQs or app description, that actual sonar has to installed from guthub, would help.

**Comment by speedy-10** [comment]
> Hi, the issue is caused by the addition of sandboxing to Sailfish, which prevents the current way used to launch the Sonar installer. There is a known fix for that, but since sandboxing causes also several other issues, the focus has been on building foundations to make the whole app work better under sandboxing. It will still take a lot of time though, so perhaps there will be need to update this one issue before any bigger changes...
I could install it via terminal. Is there progress on updating sonar to a improved version?

**Comment by hhaveri** [comment]
Thank you for the reminder, I'll try to update the app asap. Already building everything - but I will need to leave testing to a minimum.

What comes to the bigger refactoring, I have the major changes done now but still have the daunting tasks of testing & fixing each plugin and implementing importing of data from old to new app. That is, for both SFOS & Android.

**Comment by speedy-10** [comment]
The link to install sonar in Situations works now, thanks.

PS: After installation per terminal, I had to start sonar by 
'devel-su systemctl start situations-sonar'
